### ISSUE TITLE
Rozbić docker-compose na dev i produkcje

### ISSUE THREAD

**Issue by TheJimmyNowak** [knmlprz/ChatKNML#60]
Jaki jest cel tego tego zadania

Rozdzielenie docker-compose na dwa różne pliki, aby umożliwić łatwiejszy development na lokalnych środowiskach.
Jak wygląda rozwiązanie?

Dwa pliki:

 - docker-compose.dev.yml - plik deweloperski.
 - docker-compose.prod.yml - plik produkcyjny.

Plik deweloperski:
- podpina się pod API OpenAI
- I NIE zawiera embeddingów i LLMa.

Plik produkcyjny korzysta z naszego API na serwerze.

To z jakiego API się korzysta ma być konfigurowane przez zmienne środowiskowe:

    LLM_API_BASE_URL
    LLM_API_TOKEN
    EMBEDDINGS_API_BASE_URL
    EMBEDDINGS_API_TOKEN

## Rozwiązanie:

- zostaje jeden plik .env, który podmieniamy w środowisku produkcyjnym
- ustawiamy profil dev i production

**Comment by finloop** [comment]
## Jaki jest cel tego tego zadania
Rozdzielenie docker-compose na dwa różne pliki, aby umożliwić łatwiejszy development na lokalnych środowiskach.

## Jak wygląda rozwiązanie?

Dwa pliki:
- `docker-compose.dev.yml` - plik deweloperski.
- `docker-compose.prod.yml` - plik produkcyjny.

Plik deweloperski:
-  podpina się pod API OpenAI
-  I NIE zawiera embeddingów i LLMa.

Plik produkcyjny korzysta z naszego API na serwerze.

To z jakiego API się korzysta ma być konfigurowane przez zmienne środowiskowe:
- `LLM_API_BASE_URL`
- `LLM_API_TOKEN`
- `EMBEDDINGS_API_BASE_URL`
- `EMBEDDINGS_API_TOKEN`

**Comment by finloop** [comment]
^ Taka jest moja propozycja @TheJimmyNowak szczegóły zostawiam osobie która będzie to implementować. Nazwy zmiennych środowiskowych podlegają debacie, jak ktos wymyśli bardziej deskryptywne to zmienimy.

**Comment by Sygnator** [comment]
Do review:
https://github.com/knmlprz/ChatKNML/tree/docker-setup

**Comment by TheJimmyNowak** [comment]
Pomimo uruchomienia polecenia `docker compose --profile dev up` embeding api się pobiera

**Comment by finloop** [comment]
@TheJimmyNowak U mnie działa. Nie robi pobiera obrazka emedding api.

```
(base) finloop@gpu:~/projects/ChatKNML$ docker compose --profile dev up
[+] Running 14/14
 ✔ db 13 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                              28.4s
   ✔ 1f7ce2fa46ab Already exists                                                     0.0s
   ✔ 8a0c088137b8 Pull complete                                                      0.8s
   ✔ 11be68f68a2e Pull complete                                                      1.2s
   ✔ 19f13c4e1d96 Pull complete                                                      1.2s
   ✔ 43187fdc5ebc Pull complete                                                      7.2s
   ✔ a84cb0803492 Pull complete                                                      6.6s
   ✔ b50a897e2632 Pull complete                                                      6.5s
   ✔ 7bc6d5552c52 Pull complete                                                      7.3s
   ✔ c8161286a3f1 Pull complete                                                     21.8s
   ✔ e36f0ab546af Pull complete                                                     12.2s
   ✔ c2a71678092b Pull complete                                                     24.8s
   ✔ 7c23bdcac538 Pull complete                                                     13.0s
   ✔ 16648961c661 Pull complete                                                     13.0s
[+] Building 21.0s (15/15) FINISHED                                        docker:default
 => [api internal] load .dockerignore                                                0.6s
 => => transferring context: 2B                                                      0.0s
 => [api internal] load build definition from Dockerfile                             0.5s
 => => transferring dockerfile: 625B                                                 0.0s
 => [api internal] load metadata for docker.io/library/python:3.11-slim-buster       2.1s
 => [api internal] load metadata for docker.io/library/python:3.11-buster            2.2s
 => [api builder 1/6] FROM docker.io/library/python:3.11-buster@sha256:3a19b4d6ce44  0.0s
 => CACHED [api runtime 1/3] FROM docker.io/library/python:3.11-slim-buster@sha256:  0.0s
 => [api internal] load build context                                                0.2s
 => => transferring context: 24.07kB                                                 0.0s
 => CACHED [api builder 2/6] RUN pip install poetry==1.6.1                           0.0s
 => CACHED [api builder 3/6] WORKDIR /app                                            0.0s
 => [api builder 4/6] COPY pyproject.toml poetry.lock ./                             2.6s
 => [api builder 5/6] RUN touch README.md                                            3.1s
 => [api builder 6/6] RUN --mount=type=cache,target=/tmp/poetry_cache poetry instal  7.3s
 => [api runtime 2/3] COPY --from=builder /app/.venv /app/.venv                      1.9s
 => [api runtime 3/3] COPY . ./                                                      0.4s
 => [api] exporting to image                                                         0.9s
 => => exporting layers                                                              0.9s
 => => writing image sha256:8621dcee5582cb0104382bedc71841c7a072010809d7f2fdf014901  0.0s
 => => naming to docker.io/library/chatknml-api                                      0.0s
[+] Running 4/4
 ✔ Network chatknml_default          Created                                         0.5s
 ✔ Container chatknml-db-1           Created                                         1.5s
 ✔ Container chatknml-discord-bot-1  Created                                         1.5s
 ✔ Container chatknml-api-1          Created                                         0.3s
Attaching to chatknml-api-1, chatknml-db-1, chatknml-discord-bot-1
chatknml-db-1           | Error: Database is uninitialized and superuser password is not specified.
chatknml-db-1           |        You must specify POSTGRES_PASSWORD to a non-empty value for the
chatknml-db-1           |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
chatknml-db-1           |
chatknml-db-1           |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
chatknml-db-1           |        connections without a password. This is *not* recommended.
chatknml-db-1           |
chatknml-db-1           |        See PostgreSQL documentation about "trust":
chatknml-db-1           |        https://www.postgresql.org/docs/current/auth-trust.html
chatknml-db-1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
[+] Stopping 0/0
 ⠋ Container chatknml-api-1          Stopping                                        0.1s
 ⠋ Container chatknml-discord-bot-1  Stopping                                        0.1s
[+] Stopping 3/2
 ✔ Container chatknml-api-1          Stopped                                         0.8s
 ✔ Container chatknml-discord-bot-1  Stopped                                         0.7s
 ✔ Container chatknml-db-1           Stopped                                         0.0s
canceled
```

**Comment by finloop** [comment]
Standardowa odpowiedź admina nr 1. U mnie działa.

```
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
(base) finloop@gpu:~/projects/ChatKNML$ docker system prune -a --volumes
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all anonymous volumes not used by at least one container
  - all images without at least one container associated to them
  - all build cache

Are you sure you want to continue? [y/N] y
]Deleted Containers:
47aa4f601f88da7632c0977d6400124422c57d080bd30d1d06ea9428cfb44a0e
c2c5d1292b944544fb7194c6f520c1d7d83f9dbb9fcfa05e30940f40f6bf643d
9283f286b6e44c8fc39acd4bbd0adb9593015d01bcb8a3d991242121214f4617

Deleted Networks:
chatknml_default

Deleted build cache objects:
o5jcv93b423weci27bh0hkkkk
mr5dd2zo5b5cyqg8enwbaga9k
vur7qmqnykfl0xttrlqwatlan
thg67hzsr8u4zwhzm5estdk1l
jb490uymb8zix5v18dzgw58ox
v90k88ny92kr2x79s84et24ba
0yff2tzws5h15rcqg4bn3qq6w
ml55lzj44ckagny0zyoe4pe27
n2s1hvlmh5w92ysqieh824qhl
95y9hr4hif69909eol5cqxzu6
oouhdgh39rz4u57qcwgn53k0n
01edzsqadvgr9in7qj7olqxk8
qcu1ju41ixx7stuposvejix2h
ccilt8x0n2hbaiq10mpnbhqkp
rbnprkbz61va19deuyjvct7lc
cpbtc7l18j1sdb7znlv7wqea4
unzpgcsj5kiogtabrqav9i4px
rg1ha9avwjpjsff1rkk354jfc
x6bza0jgsnlh34geau0h8baqv
o46higwd04ag25jtdc3lvo5pw
grl8xtajbj8m0wo42avdjrfhd
rvizcx5rllvt22cs95rxozsk9
5xl2ez0v5zk221lag4e9k5osq
uung1rs3ebn22i8g8fg0qaz8h
q56ianssnsamx5vk8fq3u89su
mvwiao1ryu6i5mv3aow3mqabu
15eu2tayuoq5q1urbczm96st6
q7dwz05q5w2xfxetg4yjdbelh
ckikg29dy7g84f2dw2zyqd5ac
gml3bw1428x8rouzhla0in04t
vxm12ink6a7ozqr2g8uhwppgq
uctx34xbinj5ufzklca2n8lr9
tfufm8r2knwaz2hoacbodhc9k
pt4vv8nboqsn01nfm447yb3gp
o1f5220y73otvi53v4g7zblb6
ql8vjed275xuiupzrbv8eo10p
wuzl7y11qnfl304hypm20sbkt
w2giwc4b4lajqu4gq9gvmjwvz
gjxgnh12prfeacoih4jtslckm
2tmvsuhnku0nvmlh6zyrtu0ux
1kv4xtuksotenp3z51lsfggp8
00e6fxtgr1abs7rswv5rnu4pq
9emffe4lv9lrc8o8g2xu2ftpl
m6rbpwtar5tq2pjyq5gg03gvz
s6mo3o1j4vrfo7n6qy779isy6
wua0ej5klzwvkbrf29brvtot4
xzvimr6n20u2olezgwshrv3vl
3lijc95zcy91cd9mlb90q8i25
htkw2ya4rvwryny8viy8e170q
83pm1cq80eb1h3n90x5ksfsiz
861lb0fqd8bh7k31tiw3gg3mj
f2frwpi5aehry5zupjzz8kcsk
16j2ixxq3o9gh015ao3nrmmr8
3o5l85m9saf44pdyehyj69s4d

Total reclaimed space: 13.8GB
(base) finloop@gpu:~/projects/ChatKNML$ docker compose --profile dev up
[+] Running 14/14
 ✔ db 13 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                              24.2s
   ✔ 1f7ce2fa46ab Pull complete                                                      3.9s
   ✔ 8a0c088137b8 Pull complete                                                      0.6s
   ✔ 11be68f68a2e Pull complete                                                      1.8s
   ✔ 19f13c4e1d96 Pull complete                                                      2.0s
   ✔ 43187fdc5ebc Pull complete                                                      8.2s
   ✔ a84cb0803492 Pull complete                                                      7.7s
   ✔ b50a897e2632 Pull complete                                                      7.4s
   ✔ 7bc6d5552c52 Pull complete                                                      8.0s
   ✔ c8161286a3f1 Pull complete                                                     17.8s
   ✔ e36f0ab546af Pull complete                                                      8.7s
   ✔ c2a71678092b Pull complete                                                      8.8s
   ✔ 7c23bdcac538 Pull complete                                                     21.4s
   ✔ 16648961c661 Pull complete                                                      9.4s
[+] Building 95.1s (24/24) FINISHED                                        docker:default
 => [discord-bot internal] load .dockerignore                                        0.7s
 => => transferring context: 2B                                                      0.0s
 => [discord-bot internal] load build definition from Dockerfile                     0.6s
 => => transferring dockerfile: 604B                                                 0.0s
 => [api internal] load build definition from Dockerfile                             0.7s
 => => transferring dockerfile: 625B                                                 0.0s
 => [api internal] load .dockerignore                                                0.8s
 => => transferring context: 2B                                                      0.0s
 => [discord-bot internal] load metadata for docker.io/library/python:3.11-slim-bus  1.9s
 => [api internal] load metadata for docker.io/library/python:3.11-buster            1.9s
 => [api internal] load build context                                                0.5s
 => => transferring context: 24.07kB                                                 0.0s
 => [api builder 1/6] FROM docker.io/library/python:3.11-buster@sha256:3a19b4d6ce4  44.7s
 => => resolve docker.io/library/python:3.11-buster@sha256:3a19b4d6ce4402d11bb19aa1  0.8s
 => => sha256:3a19b4d6ce4402d11bb19aa11416e4a262a60a57707a5cda5787a8128 988B / 988B  0.0s
 => => sha256:35a9527e56796de39e7132531a63f13c97e77ea1ca182bd4dd47c 2.01kB / 2.01kB  0.0s
 => => sha256:5bf9a636079f0257fa52c3bbed42ec29d3b975cfd1ef2db2016c1 7.52kB / 7.52kB  0.0s
 => => sha256:ac8bb7e1a32398e26c129ce64e2ddc3e7ec6c34d93424b247f 50.45MB / 50.45MB  14.8s
 => => sha256:3b1c264c0ad4598c25048a6dbd3030086cc5c74000e11d04ac 17.58MB / 17.58MB  91.5s
 => => sha256:b1e7e053c9f6f57c6d95002167a6d57aed6aacf04dd2f8e681 51.87MB / 51.87MB  18.6s
 => => sha256:a2e1e233599c00054fb839db78b4d42e6f12f36b64280aa6 191.88MB / 191.88MB  35.0s
 => => extracting sha256:ac8bb7e1a32398e26c129ce64e2ddc3e7ec6c34d93424b247f16049f5a  1.6s
 => => sha256:0ebfe287e9761b9b7dd1703470ff3473a62fe75238f3de012821 6.15MB / 6.15MB  18.0s
 => => extracting sha256:3b1c264c0ad4598c25048a6dbd3030086cc5c74000e11d04ac27944cb1  0.4s
 => => sha256:de5c87c207fdbeb45bd9af3dfcedfa01ca8dabc9849ded7a47 22.31MB / 22.31MB  27.9s
 => => extracting sha256:b1e7e053c9f6f57c6d95002167a6d57aed6aacf04dd2f8e681cb4f74a7  1.7s
 => => sha256:7d34d7fb27b1dc3c88ed00968ed95052da3afce13640f4b19b90b1ed 244B / 244B  19.0s
 => => sha256:342382b8cc09c8dcb9c3afb12c6c6ceb2f32eec26b5083220daf 3.09MB / 3.09MB  20.1s
 => => extracting sha256:a2e1e233599c00054fb839db78b4d42e6f12f36b64280aa62d482a3ad0  4.7s
 => => extracting sha256:0ebfe287e9761b9b7dd1703470ff3473a62fe75238f3de01282165f872  0.2s
 => => extracting sha256:de5c87c207fdbeb45bd9af3dfcedfa01ca8dabc9849ded7a471db354b8  0.5s
 => => extracting sha256:7d34d7fb27b1dc3c88ed00968ed95052da3afce13640f4b19b90b1edd4  0.0s
 => => extracting sha256:342382b8cc09c8dcb9c3afb12c6c6ceb2f32eec26b5083220daf410073  0.5s
 => [api runtime 1/3] FROM docker.io/library/python:3.11-slim-buster@sha256:c46b0ae  8.6s
 => => resolve docker.io/library/python:3.11-slim-buster@sha256:c46b0ae5728c2247b99  0.8s
 => => sha256:db841a2e8ab326bf1101c5714186094fa05d3277c5b2dbcec943d 6.83kB / 6.83kB  0.0s
 => => sha256:c46b0ae5728c2247b99903098ade3176a58e274d9c7d2efeaaab3e062 988B / 988B  0.0s
 => => sha256:b94af75d4ff65c50bf1b2119bca6d0ba707037bacd0cb75314801 1.37kB / 1.37kB  0.0s
 => => sha256:8b91b88d557765cd8c6802668755a3f6dc4337b6ce15a17e485 27.14MB / 27.14MB  3.8s
 => => sha256:824416e234237961c9c5d4f41dfe5b295a3c35a671ee52889bfb0 2.78MB / 2.78MB  1.6s
 => => sha256:482d64d97d4e63625e51301e23ca7ff526afaf40710da26704d 12.00MB / 12.00MB  4.8s
 => => sha256:c87b3089b2ed5584d9a52ddf02017556958f287dd63945476fbcd1919 244B / 244B  1.9s
 => => sha256:91bdacd599c69598dd6fbd7f97f7059b565f6f3015a04b6ab9e8d 3.38MB / 3.38MB  3.3s
 => => extracting sha256:8b91b88d557765cd8c6802668755a3f6dc4337b6ce15a17e4857139e5f  1.0s
 => => extracting sha256:824416e234237961c9c5d4f41dfe5b295a3c35a671ee52889bfb08d8e2  0.2s
 => => extracting sha256:482d64d97d4e63625e51301e23ca7ff526afaf40710da26704d9ce2e1a  0.6s
 => => extracting sha256:c87b3089b2ed5584d9a52ddf02017556958f287dd63945476fbcd19195  0.0s
 => => extracting sha256:91bdacd599c69598dd6fbd7f97f7059b565f6f3015a04b6ab9e8db254a  0.3s
 => [discord-bot internal] load build context                                        0.7s
 => => transferring context: 72.88kB                                                 0.0s
 => [api builder 2/6] RUN pip install poetry==1.6.1                                 23.5s
 => [api builder 3/6] WORKDIR /app                                                   2.4s
 => [discord-bot builder 4/6] COPY pyproject.toml poetry.lock ./                     2.3s
 => [api builder 4/6] COPY pyproject.toml poetry.lock ./                             2.6s
 => [discord-bot builder 5/6] RUN touch README.md                                    4.7s
 => [api builder 5/6] RUN touch README.md                                            3.3s
 => [api builder 6/6] RUN --mount=type=cache,target=/tmp/poetry_cache poetry instal  7.0s
 => [discord-bot builder 6/6] RUN --mount=type=cache,target=/tmp/poetry_cache poetr  6.3s
 => [discord-bot runtime 2/3] COPY --from=builder /app/.venv /app/.venv              1.3s
 => [api runtime 2/3] COPY --from=builder /app/.venv /app/.venv                      1.2s
 => [discord-bot runtime 3/3] COPY . ./                                              0.8s
 => [api runtime 3/3] COPY . ./                                                      0.7s
 => [api] exporting to image                                                         3.3s
 => => exporting layers                                                              2.7s
 => => writing image sha256:4b0799f4406f38fc6e32b749f8616f9fd35847699672b0233e556cf  0.2s
 => => naming to docker.io/library/chatknml-api                                      0.4s
 => [discord-bot] exporting to image                                                 1.6s
 => => exporting layers                                                              0.6s
 => => writing image sha256:bcd60f82dfa8be78d10f5ddd7813e05cb81943308cd3afad5af5d00  0.5s
 => => naming to docker.io/library/chatknml-discord-bot                              0.5s
[+] Running 4/4
 ✔ Network chatknml_default          Created                                         0.1s
 ✔ Container chatknml-db-1           Created                                         1.2s
 ✔ Container chatknml-discord-bot-1  Created                                         1.1s
 ✔ Container chatknml-api-1          Created                                         0.2s
Attaching to chatknml-api-1, chatknml-db-1, chatknml-discord-bot-1
chatknml-db-1           | Error: Database is uninitialized and superuser password is not specified.
chatknml-db-1           |        You must specify POSTGRES_PASSWORD to a non-empty value for the
chatknml-db-1           |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
chatknml-db-1           |
chatknml-db-1           |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
chatknml-db-1           |        connections without a password. This is *not* recommended.
chatknml-db-1           |
chatknml-db-1           |        See PostgreSQL documentation about "trust":
chatknml-db-1           |        https://www.postgresql.org/docs/current/auth-trust.html
chatknml-db-1 exited with code 1
chatknml-discord-bot-1  | Traceback (most recent call last):
chatknml-discord-bot-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
chatknml-discord-bot-1  |   File "<frozen runpy>", line 88, in _run_code
chatknml-discord-bot-1  |   File "/discord_bot/bot.py", line 76, in <module>
chatknml-discord-bot-1  |     main()
chatknml-discord-bot-1  |   File "/discord_bot/bot.py", line 72, in main
chatknml-discord-bot-1  |     bot.run(os.environ["TOKEN"])
chatknml-discord-bot-1  |             ~~~~~~~~~~^^^^^^^^^
chatknml-discord-bot-1  |   File "<frozen os>", line 679, in __getitem__
chatknml-discord-bot-1  | KeyError: 'TOKEN'
chatknml-discord-bot-1 exited with code 1
chatknml-api-1          | Traceback (most recent call last):
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/environ/environ.py", line 388, in get_value
chatknml-api-1          |     value = self.ENVIRON[var_name]
chatknml-api-1          |             ~~~~~~~~~~~~^^^^^^^^^^
chatknml-api-1          |   File "<frozen os>", line 679, in __getitem__
chatknml-api-1          | KeyError: 'SECRET_KEY'
chatknml-api-1          |
chatknml-api-1          | The above exception was the direct cause of the following exception:
chatknml-api-1          |
chatknml-api-1          | Traceback (most recent call last):
chatknml-api-1          |   File "/app/.venv/bin/uvicorn", line 8, in <module>
chatknml-api-1          |     sys.exit(main())
chatknml-api-1          |              ^^^^^^
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
chatknml-api-1          |     return self.main(*args, **kwargs)
chatknml-api-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
chatknml-api-1          |     rv = self.invoke(ctx)
chatknml-api-1          |          ^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
chatknml-api-1          |     return ctx.invoke(self.callback, **ctx.params)
chatknml-api-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
chatknml-api-1          |     return __callback(*args, **kwargs)
chatknml-api-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 416, in main
chatknml-api-1          |     run(
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
chatknml-api-1          |     server.run()
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
chatknml-api-1          |     return asyncio.run(self.serve(sockets=sockets))
chatknml-api-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
chatknml-api-1          |     return runner.run(main)
chatknml-api-1          |            ^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
chatknml-api-1          |     return self._loop.run_until_complete(task)
chatknml-api-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
chatknml-api-1          |     return future.result()
chatknml-api-1          |            ^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
chatknml-api-1          |     config.load()
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
chatknml-api-1          |     self.loaded_app = import_from_string(self.app)
chatknml-api-1          |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
chatknml-api-1          |     module = importlib.import_module(module_str)
chatknml-api-1          |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
chatknml-api-1          |     return _bootstrap._gcd_import(name[level:], package, level)
chatknml-api-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
chatknml-api-1          |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
chatknml-api-1          |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
chatknml-api-1          |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
chatknml-api-1          |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
chatknml-api-1          |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
chatknml-api-1          |   File "/api/asgi.py", line 9, in <module>
chatknml-api-1          |     "http": get_asgi_application(),
chatknml-api-1          |             ^^^^^^^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/django/core/asgi.py", line 12, in get_asgi_application
chatknml-api-1          |     django.setup(set_prefix=False)
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/django/__init__.py", line 19, in setup
chatknml-api-1          |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
chatknml-api-1          |                       ^^^^^^^^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
chatknml-api-1          |     self._setup(name)
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
chatknml-api-1          |     self._wrapped = Settings(settings_module)
chatknml-api-1          |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
chatknml-api-1          |     mod = importlib.import_module(self.SETTINGS_MODULE)
chatknml-api-1          |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
chatknml-api-1          |     return _bootstrap._gcd_import(name[level:], package, level)
chatknml-api-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
chatknml-api-1          |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
chatknml-api-1          |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
chatknml-api-1          |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
chatknml-api-1          |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
chatknml-api-1          |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
chatknml-api-1          |   File "/api/settings.py", line 14, in <module>
chatknml-api-1          |     SECRET_KEY = env("SECRET_KEY")
chatknml-api-1          |                  ^^^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/environ/environ.py", line 199, in __call__
chatknml-api-1          |     return self.get_value(
chatknml-api-1          |            ^^^^^^^^^^^^^^^
chatknml-api-1          |   File "/app/.venv/lib/python3.11/site-packages/environ/environ.py", line 392, in get_value
chatknml-api-1          |     raise ImproperlyConfigured(error_msg) from exc
chatknml-api-1          | django.core.exceptions.ImproperlyConfigured: Set the SECRET_KEY environment variable
chatknml-api-1 exited with code 1
```

**Comment by finloop** [comment]
@TheJimmyNowak Temat zamykam, jeżeli to bug to otwórz issue na repo i to go zdebugujemy.
